### ISSUE TITLE
returned non-zero exit status 1

### ISSUE THREAD

**Issue by moch4602** [Ledger-Donjon/whitebox_ECDSA_attack_tool#7]
I try to run thon3 attack_challenge.py 3
but some error show
ython3 attack_challenge.py 3
Target pubkey: (51373825986355774071250980279620467994040880475046330500810086649905043895940,24310311305488748994553138095599191243412933863929305440484464503786399707769)
Traceback (most recent call last):
  File "/home/ubuntu/whitebox_ECDSA_attack_tool/whibox/attack_challenge.py", line 177, in <module>
    main()
  File "/home/ubuntu/whitebox_ECDSA_attack_tool/whibox/attack_challenge.py", line 173, in main
    ecdsa_fault_attack(args.challenge_id, args.attack, args.fast)
  File "/home/ubuntu/whitebox_ECDSA_attack_tool/whibox/attack_challenge.py", line 96, in ecdsa_fault_attack
    compile_challenge(ORIGINAL_FILENAME_A, challenge_id)
  File "/home/ubuntu/whitebox_ECDSA_attack_tool/whibox/attack_challenge.py", line 66, in compile_challenge
    subprocess.run(
  File "/usr/lib/python3.10/subprocess.py", line 524, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['gcc-10', 'drivers/main_a.c', 'drivers/mocks.c', 'challenges/3/source.c', '-o', 'main_a', '-lgmp']' returned non-zero exit status 1.

can you fix this?

**Comment by adrianthillard** [comment]
Hello

I am not able to reproduce your error. Possible causes could be that the challenges haven't been downloaded in the same directory, or maybe a missing dependency.

Could you check what issue is returned by gcc-10, by running the command directly (eg. gcc-10 drivers/main_a.c drivers/mocks.c challenges/3/source.c -o main_a -lgmp)?

**Comment by moch4602** [comment]
thank you very much
